In [8]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [9]:
data = pd.read_csv('regression_data2.csv', header=None)

In [10]:
print(data)

                          0                1                   2
0                   Country  Life expectancy                 BMI
1               Afghanistan             52.8            20.62058
2                   Albania             76.8            26.44657
3                   Algeria             75.5            24.59620
4                   Andorra             84.6            27.63048
5                    Angola             56.7            22.25083
6                   Armenia             72.3  25.355420000000002
7                 Australia             81.6            27.56373
8                   Austria             80.4  26.467409999999997
9                Azerbaijan             69.2            25.65117
10                  Bahamas             72.2            27.24594
11               Bangladesh             68.3            20.39742
12                 Barbados             75.3            26.38439
13                  Belarus             70.0            26.16443
14                  Belgi

In [11]:
data = data.loc[1:]
data_x = data[[2]]#iloc[:,0]
data_y = data[[1]]#iloc[:,1]

In [12]:
model = LinearRegression()

In [13]:
model.fit(data_x, data_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [14]:
y_pred = model.predict([[21.07931]])

In [15]:
print(y_pred)

[[60.31564716]]


In [9]:
########Boston Dataset

In [10]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston

In [11]:
boston_data = load_boston()
#print(boston_data)
x = boston_data['data']
y = boston_data['target']
print(x)
print(y)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.

In [12]:
model1 = LinearRegression()

In [13]:
model1.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [14]:
sample_house = [[2.29690000e-01, 0.00000000e+00, 1.05900000e+01, 0.00000000e+00, 4.89000000e-01,
                6.32600000e+00, 5.25000000e+01, 4.35490000e+00, 4.00000000e+00, 2.77000000e+02,
                1.86000000e+01, 3.94870000e+02, 1.09700000e+01]]

In [15]:
y_pred = model1.predict(sample_house)

In [16]:
print(y_pred)

[23.68284712]
